version: '3'
services:
    mongodb:
        build: ./mongodb
        container_name: ${MONGO_CONTAINER_NAME}
        restart: always
        ports:
            - 27017:27017
        env_file:
            - .env