version: '3'
services:
    mongodb:
        build: 
            context: .
            dockerfile: ./mongodb/Dockerfile
        container_name: ${MONGO_CONTAINER_NAME}
        restart: always
        ports:
            - 27017:27017
        env_file:
            - .env

    django:
        build: 
            context: .
            dockerfile: ./EchoWolfProject/Dockerfile
        container_name: ${DJANGO_CONTAINER_NAME}
        restart: always
        ports:
            - 80:80
        env_file:
            - .env
        depends_on:
            - mongodb
        entrypoint: >
            sh -c "
            cd /app/EchoWolfProject &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:80
            "